steps:
  # ขั้นตอนที่ 1: ตั้งค่า environment variables
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'set-env'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # สร้างไฟล์ .env.production สำหรับ React client
        echo "REACT_APP_API_URL=https://sda-server-$PROJECT_ID.run.app" > ./client/.env.production
        
        # แทนที่ PROJECT_ID ใน nginx.conf
        sed -i "s/\${PROJECT_ID}/$PROJECT_ID/g" ./client/nginx.conf

  # ขั้นตอนที่ 2: Build Strapi (Server)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-server'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sda-server:$COMMIT_SHA', './server']

  # ขั้นตอนที่ 3: Build React (Client)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-client'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sda-client:$COMMIT_SHA', './client']

  # ขั้นตอนที่ 4: Push Strapi image ไปยัง Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-server'
    args: ['push', 'gcr.io/$PROJECT_ID/sda-server:$COMMIT_SHA']

  # ขั้นตอนที่ 5: Push React image ไปยัง Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-client'
    args: ['push', 'gcr.io/$PROJECT_ID/sda-client:$COMMIT_SHA']

  # ขั้นตอนที่ 6: Deploy Strapi ไปยัง Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-server'
    args:
      - 'run'
      - 'deploy'
      - 'sda-server'
      - '--image=gcr.io/$PROJECT_ID/sda-server:$COMMIT_SHA'
      - '--region=asia-southeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=DATABASE_CLIENT=sqlite,NODE_ENV=production'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=5'

  # ขั้นตอนที่ 7: Deploy React ไปยัง Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-client'
    args:
      - 'run'
      - 'deploy'
      - 'sda-client'
      - '--image=gcr.io/$PROJECT_ID/sda-client:$COMMIT_SHA'
      - '--region=asia-southeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=5'

  # ขั้นตอนที่ 8: แสดงข้อมูล URL ของ services
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'show-urls'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Server URL: $(gcloud run services describe sda-server --region=asia-southeast1 --format='value(status.url)')"
        echo "Client URL: $(gcloud run services describe sda-client --region=asia-southeast1 --format='value(status.url)')"

# กำหนดเวลาในการ build (timeout)
timeout: '1800s'

# รายการ images ที่สร้างขึ้น
images:
  - 'gcr.io/$PROJECT_ID/sda-server:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/sda-client:$COMMIT_SHA'